### ISSUE TITLE
Spinner won't stop on template render

### ISSUE THREAD

**Issue by arnonate** [SachaG/meteor-spin#21]
I may be doing something wrong in this template... but the spinner never hides. The template loads and spinner continues to spin. I am not getting any errors in the template and all data (waiting on 2 subscriptions) has been loaded. Any suggestions?

**Comment by alexmal0916** [comment]
once template rendering is finished, we have to hide the spinner, there is any way for that in the Sacha:spin new package?

**Comment by SachaG** [comment]
You can just use an `{{#if isLoaded}}...{{/if}}`?

**Comment by alexmal0916** [comment]
so, it cannot spinning while template is rendering?

**Comment by SachaG** [comment]
Well, I'm not really sure what you mean. You can show it or not, that's basically it.

**Comment by Dashman99** [comment]
I'm not sure why this was closed, I have this same issue.  Sacha, in the Discover Meteor book you have a template called 'loading' which just has the {{> spinner}} directive.  The Router.configure specifies the loadingTemplate to be 'loading'.  This is so that the spinner is shown until the data loads from the subscription.  I too, have some routes that subscribe to some data and the spinner continues to spin even after data is loaded.
